# Generated by Django 2.0.1 on 2018-07-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('my-donations', 'my donations'), ('my-solicitations', 'my solicitations'), ('my-requests', 'my requests')], max_length=20, null=True, verbose_name='type'),
        ),
    ]
