# Generated by Django 2.0.1 on 2018-10-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification_unread'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('initials', models.CharField(blank=True, max_length=2, null=True, verbose_name='initials')),
            ],
            options={
                'verbose_name': 'unit of measurement',
                'verbose_name_plural': 'unit of measurements',
            },
        ),
    ]
