# Generated by Django 2.0.1 on 2018-10-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_unitmeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmeasurement',
            name='initials',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='initials'),
        ),
    ]
