# Generated by Django 2.0.1 on 2018-10-11 13:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181004_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
