# Generated by Django 2.0.1 on 2019-10-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0031_auto_20190910_1110'),
        ('core', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='donation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='donations.Donation'),
        ),
    ]
