# Generated by Django 2.0.1 on 2018-01-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180112_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'institution', 'verbose_name_plural': 'instituions'},
        ),
        migrations.AddField(
            model_name='institution',
            name='objectives',
            field=models.TextField(blank=True, null=True, verbose_name='objectives'),
        ),
        migrations.AddField(
            model_name='institution',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
