# Generated by Django 2.0.1 on 2018-01-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180112_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='cell phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='cell phone'),
        ),
    ]
