# Generated by Django 2.0.1 on 2018-03-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180116_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='institution',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='complement'),
        ),
        migrations.AddField(
            model_name='institution',
            name='gia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gia'),
        ),
        migrations.AddField(
            model_name='institution',
            name='ibge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IBGE'),
        ),
        migrations.AddField(
            model_name='institution',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='institution',
            name='unity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='unity'),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='person',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='complement'),
        ),
        migrations.AddField(
            model_name='person',
            name='gia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gia'),
        ),
        migrations.AddField(
            model_name='person',
            name='ibge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IBGE'),
        ),
        migrations.AddField(
            model_name='person',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='person',
            name='unity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='unity'),
        ),
    ]
