# Generated by Django 2.0.1 on 2018-03-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180313_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='cep',
            field=models.CharField(default=65421, max_length=255, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='cep',
            field=models.CharField(default=1, max_length=255, verbose_name='CEP'),
            preserve_default=False,
        ),
    ]
