# Generated by Django 2.0.1 on 2018-05-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180322_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='cell_phone',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='city',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='gia',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='ibge',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='number',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='street',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='unity',
        ),
        migrations.RemoveField(
            model_name='person',
            name='cell_phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gia',
        ),
        migrations.RemoveField(
            model_name='person',
            name='ibge',
        ),
        migrations.RemoveField(
            model_name='person',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='person',
            name='number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='street',
        ),
        migrations.RemoveField(
            model_name='person',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='person',
            name='unity',
        ),
        migrations.AddField(
            model_name='user',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='cell phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(default=1, max_length=255, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='complement'),
        ),
        migrations.AddField(
            model_name='user',
            name='gia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gia'),
        ),
        migrations.AddField(
            model_name='user',
            name='ibge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IBGE'),
        ),
        migrations.AddField(
            model_name='user',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='neighborhood'),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='street'),
        ),
        migrations.AddField(
            model_name='user',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='user',
            name='unity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='unity'),
        ),
    ]
