# Generated by Django 2.0.1 on 2019-10-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190910_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='rate'),
        ),
    ]
