# Generated by Django 2.0.1 on 2019-10-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='rate'),
        ),
    ]
