# Generated by Django 2.0.1 on 2018-10-04 13:41

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_unitmeasurement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone')),
                ('cell_phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='cell phone')),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True, verbose_name='neighborhood')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='street')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='number')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='complement')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('unity', models.CharField(blank=True, max_length=255, null=True, verbose_name='unity')),
                ('ibge', models.CharField(blank=True, max_length=255, null=True, verbose_name='IBGE')),
                ('gia', models.CharField(blank=True, max_length=255, null=True, verbose_name='gia')),
                ('cep', models.CharField(max_length=255, verbose_name='CEP')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to=core.utils.img_path, verbose_name='main photo')),
                ('quantity', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='quatity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demands', to=settings.AUTH_USER_MODEL)),
                ('unit_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_demands', to='core.UnitMeasurement')),
            ],
            options={
                'verbose_name': 'demand',
                'verbose_name_plural': 'demands',
                'ordering': ['-created_at'],
            },
        ),
    ]
