# Generated by Django 2.0.1 on 2019-01-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0003_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='status',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='status'),
        ),
    ]
