# Generated by Django 2.0.1 on 2019-01-14 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comment'),
        ('demands', '0004_demand_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='quatity'),
        ),
        migrations.AddField(
            model_name='gift',
            name='unit_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_gifts', to='core.UnitMeasurement'),
        ),
    ]
