# Generated by Django 2.0.1 on 2019-07-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0005_auto_20190114_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Ativa'), ('I', 'Inválida'), ('C', 'Finalizada'), ('O', 'Em Espera')], default='A', max_length=2, null=True, verbose_name='status'),
        ),
    ]
