# Generated by Django 2.0.1 on 2019-09-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comment'),
        ('demands', '0007_auto_20190910_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_tags', to='demands.Demand')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_demands', to='core.Tag')),
            ],
            options={
                'verbose_name': 'Tag of Demand',
                'verbose_name_plural': 'Tags of Demands',
            },
        ),
    ]
