# Generated by Django 2.0.1 on 2018-05-23 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True, verbose_name='neighborhood')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='street')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='number')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='complement')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('unity', models.CharField(blank=True, max_length=255, null=True, verbose_name='unity')),
                ('ibge', models.CharField(blank=True, max_length=255, null=True, verbose_name='IBGE')),
                ('gia', models.CharField(blank=True, max_length=255, null=True, verbose_name='gia')),
                ('cep', models.CharField(max_length=255, verbose_name='CEP')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('validity', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donator', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'donations',
                'verbose_name': 'donation',
                'ordering': ['-created_at'],
            },
        ),
    ]
