# Generated by Django 2.0.1 on 2018-05-27 23:12

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.img_path, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='donation',
            name='validity_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
