# Generated by Django 2.0.1 on 2018-06-20 12:18

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20180527_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='photo',
        ),
        migrations.AddField(
            model_name='donation',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.img_path, verbose_name='main photo'),
        ),
        migrations.AddField(
            model_name='donation',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.img_path, verbose_name='photos'),
        ),
    ]
