# Generated by Django 2.0.1 on 2018-07-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20180708_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
