# Generated by Django 2.0.1 on 2018-07-08 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0007_auto_20180708_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('validity', models.DateField(blank=True, null=True)),
                ('validity_hour', models.TimeField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'solicitations',
                'ordering': ['-created_at'],
                'verbose_name': 'solicitation',
            },
        ),
    ]
