# Generated by Django 2.0.1 on 2018-07-08 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_solicitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitations', to='donations.Donation'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
