# Generated by Django 2.0.1 on 2018-07-10 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag'),
        ('donations', '0009_auto_20180708_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_tags', to='donations.Donation')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_donations', to='core.Tag')),
            ],
        ),
    ]
