# Generated by Django 2.0.1 on 2018-07-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_donationtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'solicited'), ('A', 'accepted'), ('R', 'rejected')], default='S', max_length=1, null=True, verbose_name='status'),
        ),
    ]
