# Generated by Django 2.0.1 on 2018-07-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_auto_20180713_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
