# Generated by Django 2.0.1 on 2018-08-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0017_auto_20180809_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Ativa'), ('I', 'Inválida')], default='A', max_length=1, null=True, verbose_name='status'),
        ),
    ]
