# Generated by Django 2.0.1 on 2018-08-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_donation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_valid',
        ),
    ]
