# Generated by Django 2.0.1 on 2018-09-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0019_remove_donation_is_valid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationtags',
            options={'verbose_name': 'Tag of Donation', 'verbose_name_plural': 'Tags of Donations'},
        ),
    ]
