# Generated by Django 2.0.1 on 2018-10-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0021_auto_20181011_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'Solicitada'), ('A', 'Aceita'), ('R', 'Rejeitada'), ('NA', 'Não respondida'), ('I', 'Inválida'), ('O', 'Em Espera')], default='S', max_length=1, null=True, verbose_name='status'),
        ),
    ]
