# Generated by Django 2.0.1 on 2018-10-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0023_solicitation_reason_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
