# Generated by Django 2.0.1 on 2018-11-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0025_auto_20181107_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Criada'), ('A', 'Aceita'), ('R', 'Rejeitada'), ('I', 'Inválida'), ('O', 'Em Espera'), ('C', 'Finalizada')], default='C', max_length=1, null=True, verbose_name='status'),
        ),
    ]
