# Generated by Django 2.0.1 on 2018-11-09 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0027_auto_20181107_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='donations.Donation'),
        ),
    ]
