# Generated by Django 2.0.1 on 2018-12-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0029_auto_20181119_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Ativa'), ('I', 'Inválida'), ('C', 'Finalizada'), ('O', 'Em Espera')], default='A', max_length=1, null=True, verbose_name='status'),
        ),
    ]
