# Generated by Django 2.0.1 on 2019-09-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0030_auto_20181206_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='cep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CEP'),
        ),
    ]
